version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: maydls-postgres-dev
    environment:
      POSTGRES_DB: maydls
      POSTGRES_USER: maydls_user
      POSTGRES_PASSWORD: maydls_pass
    ports:
      - "5443:5432"
    volumes:
      - ../db-dev:/var/lib/postgresql/data
    restart: unless-stopped

  yt-dlp:
    build:
      context: .
      dockerfile: Dockerfile.yt-dlp
    container_name: maydls-yt-dlp
    volumes:
      - ../downloads:/downloads
    entrypoint: [ "tail", "-f", "/dev/null" ]  # Keep container alive
    restart: unless-stopped